# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_description.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_description(object):
    def setupUi(self, Dialog_description):
        Dialog_description.setObjectName("Dialog_description")
        Dialog_description.resize(1121, 450)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_description)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_description_buttons = QtWidgets.QGridLayout()
        self.gridLayout_description_buttons.setObjectName("gridLayout_description_buttons")
        self.pushButton_description_reset_all = QtWidgets.QPushButton(Dialog_description)
        self.pushButton_description_reset_all.setObjectName("pushButton_description_reset_all")
        self.gridLayout_description_buttons.addWidget(self.pushButton_description_reset_all, 1, 1, 1, 1)
        self.pushButton_description_check_all = QtWidgets.QPushButton(Dialog_description)
        self.pushButton_description_check_all.setObjectName("pushButton_description_check_all")
        self.gridLayout_description_buttons.addWidget(self.pushButton_description_check_all, 1, 0, 1, 1)
        self.pushButton_description_save = QtWidgets.QPushButton(Dialog_description)
        self.pushButton_description_save.setObjectName("pushButton_description_save")
        self.gridLayout_description_buttons.addWidget(self.pushButton_description_save, 3, 0, 1, 1)
        self.pushButton_description_close = QtWidgets.QPushButton(Dialog_description)
        self.pushButton_description_close.setObjectName("pushButton_description_close")
        self.gridLayout_description_buttons.addWidget(self.pushButton_description_close, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(Dialog_description)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_description_buttons.addWidget(self.line, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_description_buttons, 1, 0, 1, 1)
        self.scrollArea_description = QtWidgets.QScrollArea(Dialog_description)
        self.scrollArea_description.setWidgetResizable(True)
        self.scrollArea_description.setObjectName("scrollArea_description")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1097, 344))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_description_check_box = QtWidgets.QGridLayout()
        self.gridLayout_description_check_box.setObjectName("gridLayout_description_check_box")
        self.gridLayout.addLayout(self.gridLayout_description_check_box, 0, 0, 1, 1)
        self.scrollArea_description.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea_description, 0, 0, 1, 1)

        self.retranslateUi(Dialog_description)
        QtCore.QMetaObject.connectSlotsByName(Dialog_description)

    def retranslateUi(self, Dialog_description):
        _translate = QtCore.QCoreApplication.translate
        Dialog_description.setWindowTitle(_translate("Dialog_description", "Список режимов"))
        self.pushButton_description_reset_all.setText(_translate("Dialog_description", "Снять всё"))
        self.pushButton_description_check_all.setText(_translate("Dialog_description", "Выбрать всё"))
        self.pushButton_description_save.setText(_translate("Dialog_description", "Сохранить"))
        self.pushButton_description_close.setText(_translate("Dialog_description", "Закрыть"))
